[build]
   command = "npm install --production=false && npm run build"
   publish = "dist"

[[redirects]]
   from = "/api/*"
   to = "/api/:splat"
   status = 200

[[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200
